### PR TITLE
feat: typescript define file.

### PR DESCRIPTION
**Pull request by wujun4code**

### CODE REVIEW

**Comment by iansinnott** [comment]
Awesome, thanks @wujun4code

**Comment by wujun4code** [comment]
@iansinnott thanks for your awesome works. This lib help me a lot.

**Comment by wujun4code** [comment]
and could you publish it to [npm](https://www.npmjs.com/package/jstz)? 
thanks.

**Comment by iansinnott** [comment]
Ah, yes! Forgot about that. 1.0.8 is published :)

**Comment by wujun4code** [comment]
Thanks again.

Yours.

**Comment by silviogutierrez** [comment]
Hi there,

Just a headed up, this typings file will break if you're using `noImplicitAny` as an option.

`name()` needs a return type annotation. So 

```typescript
 class TimeZone {
     name(): string;
 }
```

Hope that helps,

Silvio

**Pull request merged**
